import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const sounds = [
    {
      index: 1,
      name: 'beepboop',
      location: '/beepboop.wav'
    }
  ]

  const play = e => {
    e.preventDefault();
    console.log(e.target.key);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>td_sounds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.buttonField}>
          {sounds.map(s => {
            return (
              <button 
                className={styles.button} 
                key={s.index}
                value={'this'}
                onClick={e => play(e)}
              >
                {s.name}
              </button>
            )})}
        </div>
      </main>
    </div>
  )
}
