import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const sounds = [
    {
      index: 0,
      name: 'beepboop',
      location: '/beepboop.wav',
      icon: "fas fa-bell fa-5x"
    },
    {
      index: 1,
      name: 'heartbeat',
      location: '/heartbeat.wav',
      icon: "fas fa-heartbeat fa-5x"
    },
    {
      index: 2,
      name: 'rocket',
      location: '/rocket.wav',
      icon: "fas fa-rocket fa-5x"
    },
    {
      index: 3,
      name: 'transition',
      location: '/transition.wav',
      icon: "fas fa-arrow-circle-right fa-5x"
    },
    {
      index: 4,
      name: 'trumpet',
      location: '/trumpet.wav',
      icon: "fas fa-chess-king fa-5x"
    },
    {
      index: 5,
      name: 'whoosh',
      location: '/whoosh.wav',
      icon: "fas fa-wind fa-5x"
    },
    {
      index: 6,
      name: 'airhorn',
      location: '/airhorn.mp3',
      icon: "fas fa-bullhorn fa-5x"
    },
    {
      index: 7,
      name: 'alright',
      location: '/alright.mp3',
      image: "mm.jpeg",
      mm: true
    },
    {
      index: 7,
      name: 'whoawhoa',
      location: '/whoawhoa.m4a',
      image: "whoawhoa.png",
      mm: true
    },
  ]

  const play = s => {
    const el = document.getElementById(s);
    if (!el.paused) {
      el.pause();
      el.src = el.src;
    } else {
      el.play();
      el.style.background = 'rbg(0,0,0,.35)'
      console.log(`el.classList`, el.className);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>td_sounds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <main>
        <div className={styles.buttonField}>
          {sounds.map(s => {
            return (
              <button 
                className={styles.button} 
                key={s.index}
                onClick={() => {play(s.name)}}
              >
                {s.icon != undefined ? <i className={s.icon}></i> : <img src={s.image} alt={s.name}/>}
                <audio id={s.name} src={s.location} preload="none"></audio>
              </button>
            )})}
        </div>
      </main>
    </div>
  )
}
